[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

lib_deps = lvgl/lvgl@^8.3.11

src_filter = +<*> +<components/lvgl/src/lv_font/*.c>